theme = "landing-page-hugo"
baseurl = "http://yourdomain.com"
languageCode = "en-us"
title = "Open Source Day 2016"
canonifyUrls = "true"

[params]
    description = "Coding for Humanity"
    custom_css = ["css/local.css"]

[params]
    description = "History"
    file = ["content/history/history.md"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:bushbama@whitehouse.gov"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    icon = "linkedin"
    url = "http://linkedin.com/in/yourusername"
